#!/bin/sh
# postinst script for nagios

set -e

case "$1" in
    configure)
    if ! getent passwd nagios > /dev/null ; then
        echo 'Adding system-user for nagios' 1>&2
        adduser --system --group --home /var/lib/nagios \
        --disabled-login --force-badname nagios > /dev/null
    fi

    mkdir -p /var/lib/nagios
    mkdir -p /var/lib/nagios/rw
    chown -R nagios:nagios /var/lib/nagios

    mkdir -p /var/run/nagios
    chown nagios:nagios /var/run/nagios

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload
	if [ "X$(systemctl is-active nagios.service)" = "Xactive" ] ; then
		echo "Restarting nagios.service"
		systemctl restart nagios.service
	fi

    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
