#!/bin/sh
# postrm script for nagios
#
# see: dh_installdeb(1)

set -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    purge|remove)
    deluser --system nagios 
    ;;
    upgrade)
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
    fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
